# Generated by rust2rpm 26
%bcond_without check

%global debug_package %{nil}
%global crate iamb
%global cargo_install_lib 0

Name:           iamb
Version:        0.0.11~alpha.1
Release:        %autorelease
Summary:        Matrix chat client that uses Vim keybindings
License:        Apache-2.0

URL:            https://github.com/ulyssa/iamb
Source:         %{url}/archive/refs/tags/v%(v=%{version}; echo ${v//\~/-}).tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A Matrix chat client that uses Vim keybindings.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

install -Dpm644 %{name}.desktop %{buildroot}%{_datadir}/applications/%{name}.desktop
install -Dpm644 config.example.toml %{buildroot}%{_datadir}/%{name}/config.example.toml

install -Dpm644 docs/%{name}.1 %{buildroot}%{_mandir}/man1/%{name}.1
install -Dpm644 docs/%{name}.5 %{buildroot}%{_mandir}/man5/%{name}.5

install -Dpm644 docs/%{name}-256x256.png %{buildroot}%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
install -Dpm644 docs/%{name}-512x512.png %{buildroot}%{_datadir}/icons/hicolor/512x512/apps/%{name}.png
install -Dpm644 docs/%{name}.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/%{name}
%{_mandir}/man1/%{name}.1*
%{_mandir}/man5/%{name}.5*
%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
%{_datadir}/icons/hicolor/512x512/apps/%{name}.png
%{_datadir}/icons/hicolor/scalable/apps/%{name}.svg
%{_datadir}/%{name}/config.example.toml
%{_datadir}/applications/%{name}.desktop

%changelog
%autochangelog
