# Generated by rust2rpm 26
%bcond_without check

%global debug_package %{nil}
%global crate iamb
%global cargo_install_lib 0

Name:           iamb
Version:        0.0.9
Release:        %autorelease
Summary:        Matrix chat client that uses Vim keybindings
License:        Apache-2.0

URL:            https://github.com/ulyssa/iamb
Source:         %{url}/archive/refs/tags/v%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A Matrix chat client that uses Vim keybindings.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc CONTRIBUTING.md
%doc PACKAGING.md
%doc README.md
%{_bindir}/iamb

%changelog
%autochangelog
