# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate spin_sleep

Name:           rust-spin_sleep
Version:        1.3.0
Release:        %autorelease
Summary:        Accurate sleeping

License:        Apache-2.0
URL:            https://crates.io/crates/spin_sleep
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          spin_sleep-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Accurate sleeping. Only use native sleep as far as it can be trusted,
then spin.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nondeterministic_tests-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nondeterministic_tests-devel %{_description}

This package contains library source intended for building other packages which
use the "nondeterministic_tests" feature of the "%{crate}" crate.

%files       -n %{name}+nondeterministic_tests-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
