# Generated by go2rpm 1.11.1
%bcond_without check

# https://github.com/sentriz/cliphist
%global goipath         github.com/sentriz/cliphist
Version:                0.6.1

%gometa -L -f

%global common_description %{expand:
Wayland clipboard manager with support for multimedia.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md version.txt readme.md

Name:           cliphist
Release:        %autorelease
Summary:        Wayland clipboard manager with support for multimedia

License:        GPL-3.0-only
URL:            https://github.com/sentriz/cliphist
Source:         %{gosource}

BuildRequires: golang(github.com/rogpeppe/go-internal/testscript)
BuildRequires: golang(go.etcd.io/bbolt)
BuildRequires: golang(golang.org/x/image/bmp)

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/cliphist %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG.md version.txt readme.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
