# Generated by rust2rpm 26
%bcond_without check

%global commit 148bca7982dc19807b14a3c5bb531912120e8210
%global snapdate 20240616

%global crate hsize
%global cargo_install_lib 0

Name:           hsize
Version:        0^%{snapdate}
Release:        %autorelease
Summary:        Convert file sizes to and from human-readable units
License:        LGPL-3-only

URL:            https://github.com/ErrorNoInternet/hsize
Source:         %{url}/archive/%{commit}/%{name}-%{commit}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  (crate(clap/default) >= 4.0.0 with crate(clap/default) < 5.0.0~)
BuildRequires:  (crate(clap/derive) >= 4.0.0 with crate(clap/derive) < 5.0.0~)
BuildRequires:  (crate(clap/env) >= 4.0.0 with crate(clap/env) < 5.0.0~)
BuildRequires:  (crate(num-derive/default) >= 0.0.0 with crate(num-derive/default) < 1.0.0~)
BuildRequires:  (crate(num-traits/default) >= 0.0.0 with crate(num-traits/default) < 1.0.0~)
BuildRequires:  (crate(oorandom/default) >= 11.0.0 with crate(oorandom/default) < 12.0.0~)
BuildRequires:  (crate(regex/default) >= 1.0.0 with crate(regex/default) < 2.0.0~)

%global _description %{expand:
Convert file sizes to and from human-readable units.}

%description %{_description}

%package bash-completion
BuildArch:      noarch
Summary:        Bash completion files for %{name}
Provides:       %{name}-bash-completion = %{version}-%{release}

Requires:       bash-completion
Requires:       %{name} = %{version}-%{release}

%description bash-completion
This package installs Bash completion files for %{name}

%package fish-completion
BuildArch:      noarch
Summary:        Fish completion files for %{name}
Provides:       %{name}-fish-completion = %{version}-%{release}

Requires:       fish
Requires:       %{name} = %{version}-%{release}

%description fish-completion
This package installs Fish completion files for %{name}

%package zsh-completion
BuildArch:      noarch
Summary:        Zsh completion files for %{name}
Provides:       %{name}-zsh-completion = %{version}-%{release}

Requires:       zsh
Requires:       %{name} = %{version}-%{release}

%description zsh-completion
This package installs Zsh completion files for %{name}

%prep
%autosetup -n %{crate}-%{commit} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

mkdir -p %{buildroot}%{_mandir}/man1
cp man/hsize* %{buildroot}%{_mandir}/man1
install -Dm644 completions/hsize.bash %{buildroot}%{_datadir}/bash-completion/completions/hsize
install -Dm644 completions/hsize.fish %{buildroot}%{_datadir}/fish/vendor_completions.d/hsize.fish
install -Dm644 completions/hsize.zsh %{buildroot}%{_datadir}/zsh/site-functions/_hsize

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/hsize
%{_mandir}/man1/hsize*.1*

%files bash-completion
%{_datadir}/bash-completion/completions/hsize

%files zsh-completion
%{_datadir}/zsh/site-functions/_hsize

%files fish-completion
%{_datadir}/fish/vendor_completions.d/hsize.fish

%changelog
%autochangelog
