# Generated by rust2rpm 26
%bcond_without check

%global crate onefetch
%global cargo_install_lib 0

Name:           onefetch
Version:        2.22.0
Release:        %autorelease
Summary:        Command-line Git information tool
License:        MIT

URL:            https://github.com/o2sh/onefetch
Source:         %{url}/archive/refs/tags/%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  cmake
BuildRequires:  git

%global _description %{expand:
Command-line Git information tool.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install
install -Dpm644 docs/onefetch.1 %{buildroot}%{_mandir}/man1/onefetch.1

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.md
%license resources/license.cache.zstd
%license src/info/license.rs
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc README.md
%{_bindir}/onefetch
%{_mandir}/man1/onefetch.1*

%changelog
%autochangelog
