# Generated by go2rpm 1.14.0
%bcond check 0
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/abenz1267/walker
%global goipath         github.com/abenz1267/walker
Version:                1.0.0~beta~9

%gometa -L -f

%global common_description %{expand:
A fast, customizable application launcher built with GTK4 and Rust, designed
for Linux desktop environments. Walker provides a clean, modern interface for
launching applications, running commands, performing calculations, and more.}

%global golicenses      LICENSE
%global godocs          README.md cmd/version.txt

Name:           walker
Release:        1%{?dist}
Summary:        Multi-Purpose Launcher with a lot of features

License:        GPL-3.0-only
URL:            %{gourl}
Source:         %(s=%{gosource}; echo ${s//\~/-})

BuildRequires:  git
BuildRequires:  pkgconfig(cairo-gobject)
BuildRequires:  pkgconfig(gdk-pixbuf-2.0)
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(gobject-introspection-1.0)
BuildRequires:  pkgconfig(graphene-1.0)
BuildRequires:  pkgconfig(gtk4)
BuildRequires:  pkgconfig(gtk4-layer-shell-0)
BuildRequires:  pkgconfig(pango)
BuildRequires:  pkgconfig(vips)

Requires:       gsettings-desktop-schemas
Requires:       libglvnd-gles
Requires:       wayland-devel

Recommends:     fd-find
Recommends:     qalc
Recommends:     slurp
Recommends:     wl-clipboard
Recommends:     xdg-utils

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
go mod vendor
%endif

%if %{without bootstrap}
%build
%gobuild -o %{gobuilddir}/bin/%{name} %{goipath}/cmd
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

chmod -R u+w %{gobuilddir}/pkg
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE vendor/modules.txt
%doc README.md cmd/version.txt
%{_bindir}/*
%endif

%gopkgfiles

%changelog
%autochangelog
