%global _default_patch_fuzz 2

# Generated by rust2rpm 26
%bcond_without check

%global crate satty
%global cargo_install_lib 0

Name:           satty
Version:        0.12.0
Release:        %autorelease
Summary:        Modern Screenshot Annotation
License:        MPL-2.0

URL:            https://github.com/gabm/satty
Source:         %{url}/archive/refs/tags/v%{version}.tar.gz
Patch0:         remove-notifications.diff

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  fontconfig-devel
BuildRequires:  libepoxy-devel
BuildRequires:  gdk-pixbuf2-devel
BuildRequires:  pango-devel
BuildRequires:  cairo-gobject-devel
BuildRequires:  gtk4-devel
BuildRequires:  libadwaita-devel

%global _description %{expand:
Modern Screenshot Annotation. A Screenshot Annotation Tool inspired by
Swappy and Flameshot.}

%description %{_description}

%prep
%autosetup -n Satty-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install
install -Dm644 satty.desktop %{buildroot}%{_datarootdir}/applications/satty.desktop

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/satty
%{_datarootdir}/applications/satty.desktop

%changelog
%autochangelog
