# Generated by rust2rpm 26
%bcond_without check

%global crate git-graph
%global cargo_install_lib 0

Name:           git-graph
Version:        0.6.0
Release:        %autorelease
Summary:        Command line tool to show clear git graphs arranged for your branching model

License:        MIT

URL:            https://github.com/mlange-42/git-graph
Source:         %{url}/archive/refs/tags/%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Command line tool to show clear git graphs arranged for your branching
model.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/git-graph

%changelog
%autochangelog
