# Generated by rust2rpm 26
%bcond_without check

%global crate wallust
%global cargo_install_lib 0
%global crate_version 3.0.0-beta

Name:           wallust
Version:        3.0.0~beta
Release:        %autorelease
Summary:        Generate a 16 color scheme based on an image
License:        MIT

URL:            https://codeberg.org/explosion-mental/wallust
Source:         %{url}/archive/%{crate_version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Generate a 16 color scheme based on an image.}

%description %{_description}

%prep
%autosetup -n %{crate} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%doc v3.md
%{_bindir}/wallust

%changelog
%autochangelog
