# Generated by go2rpm 1.17.1
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/abenz1267/elephant
%global goipath         github.com/abenz1267/elephant
Version:                1.0.5

%gometa -L -f

%global common_description %{expand:
Elephant acts as a unified backend service that aggregates data from various
sources (desktop applications, files, clipboard history, etc.) and provides a
consistent interface for frontend applications like custom launchers,
productivity tools, or desktop widgets.}

%global golicenses      LICENSE
%global godocs          README.md cmd/elephant/version.txt

Name:           elephant
Release:        %autorelease
Summary:        Unified backend service that aggregates data

License:        GPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
go mod vendor
%endif

%if %{without bootstrap}
%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE vendor/modules.txt
%doc README.md cmd/elephant/version.txt
%{_bindir}/*
%endif

%gopkgfiles

%changelog
%autochangelog
