# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global features -n -f ffmpeg,pulse,mpris

Name:           songrec
Version:        0.6.0
Release:        %autorelease
Summary:        Open-source Shazam client for Linux, written in Rust

SourceLicense:  GPL-3.0-or-later
License:        (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT) AND GPL-3.0+ AND Apache-2.0 AND GPL-3.0-or-later AND (MIT OR Apache-2.0 OR Zlib) AND MPL-2.0 AND BSD-3-Clause AND (MIT OR Apache-2.0) AND MIT AND (Zlib OR Apache-2.0 OR MIT) AND (BSD-2-Clause OR MIT OR Apache-2.0) AND (Unlicense OR MIT) AND (BSD-3-Clause OR MIT OR Apache-2.0) AND (Apache-2.0 OR MIT)

URL:            https://github.com/marin-m/SongRec
Source:         %{url}/archive/%{version}/%{name}-%{version}.tar.gz
Patch:          songrec-improvements.diff

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  pkgconfig(alsa)
BuildRequires:  pkgconfig(atk)
BuildRequires:  pkgconfig(cairo)
BuildRequires:  pkgconfig(cairo-gobject)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(gdk-3.0)
BuildRequires:  pkgconfig(gdk-pixbuf-2.0)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(pango)
BuildRequires:  pulseaudio-libs

%global _description %{expand:
An open-source Shazam client for Linux, written in Rust.}

%description %{_description}

%prep
%autosetup -n SongRec-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build %{features}
%{cargo_license_summary %{features}}
%{cargo_license %{features}} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install %{features}

%if %{with check}
%check
%cargo_test %{features}
%endif

%files
%license LICENSE LICENSE.dependencies cargo-vendor.txt
%doc README.md
%{_bindir}/songrec

%changelog
%autochangelog
