# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           songrec
Version:        0.4.3
Release:        %autorelease
Summary:        Open-source Shazam client for Linux, written in Rust

SourceLicense:  GPL-3.0-or-later
License:        GPL-3.0-or-later

URL:            https://github.com/marin-m/SongRec
Source:         %{url}/archive/%{version}/%{name}-%{version}.tar.gz
Patch:          songrec-improvements.diff

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  pkgconfig(alsa)
BuildRequires:  pkgconfig(atk)
BuildRequires:  pkgconfig(cairo)
BuildRequires:  pkgconfig(cairo-gobject)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(gdk-3.0)
BuildRequires:  pkgconfig(gdk-pixbuf-2.0)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(pango)
BuildRequires:  pulseaudio-libs

%global _description %{expand:
An open-source Shazam client for Linux, written in Rust.}

%description %{_description}

%prep
%autosetup -n SongRec-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE LICENSE.dependencies cargo-vendor.txt
%doc README.md
%{_bindir}/songrec

%changelog
%autochangelog
