# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/magisterquis/connectproxy
%global goipath         github.com/magisterquis/connectproxy
%global commit          3582e84f0c9b7b32dca59adfb152d77d9fa2f8c2

%gometa -L -f

%global common_description %{expand:
Package connectproxy implements a proxy.Dialer which uses HTTP(s) CONNECT
requests.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           golang-github-magisterquis-connectproxy
Version:        0
Release:        %autorelease -p
Summary:        Implements a proxy.Dialer which uses HTTP(s) CONNECT requests

License:        Zlib
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
