%global _default_patch_fuzz 2

# Generated by rust2rpm 26
%bcond_without check

%global crate hwatch
%global cargo_install_lib 0

Name:           hwatch
Version:        0.3.13
Release:        %autorelease
Summary:        Modern alternative to the watch command
License:        MIT

URL:            https://github.com/blacknon/hwatch
Source:         %{url}/archive/refs/tags/%{version}.tar.gz

Patch0:         remove-help-banner.diff
Patch1:         precise-intervals.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A modern alternative to the watch command, records the differences in
execution results and can check this differences at after.}

%description %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/hwatch

%changelog
%autochangelog
