# Generated by rust2rpm 26
%bcond_without check

%global debug_package %{nil}
%global crate stylua
%global cargo_install_lib 0

Name:           stylua
Version:        0.20.0
Release:        %autorelease
Summary:        Code formatter for Lua
License:        MPL-2.0

URL:            https://github.com/JohnnyMorganz/StyLua
Source:         %{url}/archive/refs/tags/v%{version}.tar.gz
Patch:          stylua-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
A code formatter for Lua.}

%description %{_description}

%prep
%autosetup -n StyLua-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.md
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc CHANGELOG.md
%doc README.md
%{_bindir}/stylua

%changelog
%autochangelog
