# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate keyframe

Name:           rust-keyframe
Version:        1.1.1
Release:        %autorelease
Summary:        Simple library for animation in Rust

License:        MIT
URL:            https://crates.io/crates/keyframe
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
Patch:          keyframe-fix-metadata.diff
# Remove failing test in doc comment
Patch:          keyframe-remove-test.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A simple library for animation in Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mint-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mint-devel %{_description}

This package contains library source intended for building other packages which
use the "mint" feature of the "%{crate}" crate.

%files       -n %{name}+mint-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mint_types-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mint_types-devel %{_description}

This package contains library source intended for building other packages which
use the "mint_types" feature of the "%{crate}" crate.

%files       -n %{name}+mint_types-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1

# Remove examples/ since those aren't going to be used,
# and they include an extra `ggez` dependency.
rm -rf examples

%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
